/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.frmdelLoad;
import GUI.msgBox;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
/**
 *
 * @author miw
 */
public class DeletePanel extends javax.swing.JFrame {

    
    int productId;
    double invValue;
    int proqty;
    boolean delStatus;
    Timer timer;
    int i = 0;
    frmdelLoad delLoad = new frmdelLoad();
    /**
     * Creates new form DeletePanel3
     */
    public DeletePanel() {
        initComponents();
    }
    
     public DeletePanel(int productId) {
        this.productId = productId;
        initComponents();
        loadData(productId);
        //btnConfirm.setEnabled(false);
    }//constructor w/parameter

     
     //METHOD TO PLAY EXCLAMATION SOUNd
    private void playExclamation(){
        final Runnable runnable =
        (Runnable) Toolkit.getDefaultToolkit().getDesktopProperty("win.sound.asterisk");
        if (runnable != null) runnable.run();
    }//END METHOD
     
     public void loadData(int n){
      n=n-1;
      String strPath = "C:/Inventory.txt";
      String line;
      try (BufferedReader br = new BufferedReader(new FileReader(strPath))) {
          for (int i = 0; i < n; i++)
              br.readLine();
          line = br.readLine();
          System.out.println(line);
          String[] myData = line.split(",");
          System.out.println("Product ID     : " + myData[0]);
          System.out.println("Product Type   : " + myData[1]);
          System.out.println("Product Name   : " + myData[2]);
          System.out.println("Product Qty    : " + myData[3]);
          System.out.println("Product Price  : " + myData[4]);
          
          setTitle("Remove Product with ID : " + myData[0] + " ?");
          ctprodId.setText(myData[0]);
          ctprodType.setText(myData[1]);
          ctprodName.setText(myData[2]);
          ctprodQty.setText(myData[3]);
          ctprodPrice.setText(myData[4]);
          
          int Qty = Integer.parseInt(myData[3]);
          double price = Double.parseDouble(myData[4]);
          invValue = Qty*price;
          proqty = Qty;
          }
      catch(IOException e){
        System.out.println(e);
      }//END TRY CATCH
        
    }//END METHOD
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ctprodId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ctprodType = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ctprodName = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        ctprodQty = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        ctprodPrice = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 102));
        setUndecorated(true);

        ctprodId.setText("ctprodId");

        jLabel2.setBackground(new java.awt.Color(204, 0, 102));
        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel2.setText("REMOVE PRODUCT");

        ctprodType.setText("ctprodType");

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Confirm delete product?");

        ctprodName.setText("ctprodName");

        btnConfirm.setBackground(new java.awt.Color(204, 204, 204));
        btnConfirm.setForeground(new java.awt.Color(0, 0, 0));
        btnConfirm.setText("CONFIRM");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        ctprodQty.setText("ctprodQty");

        btnCancel.setBackground(new java.awt.Color(204, 204, 204));
        btnCancel.setForeground(new java.awt.Color(0, 0, 0));
        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        ctprodPrice.setText("ctprodPrice");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setText("Product Detail");

        jLabel4.setText("Product ID :");

        jLabel5.setText("Product Name :");

        jLabel6.setText("Quantity :");

        jLabel7.setText("Price :");

        jLabel8.setText("Type :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ctprodId)
                            .addComponent(ctprodType)
                            .addComponent(ctprodName)
                            .addComponent(ctprodQty)
                            .addComponent(ctprodPrice)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnConfirm)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ctprodId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ctprodType))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ctprodName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ctprodQty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ctprodPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnCancel))
                .addGap(26, 26, 26))
        );

        setSize(new java.awt.Dimension(402, 302));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    //btnConfirm.setEnabled(true);
    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        timer = new Timer(100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                  i++;
                    if(i==1){
                        dispose();//CLOSE FRAME
                        delLoad.setVisible(true);
                        delLoad.lbldelLoad.setText("Processing . . . ");
                    }//END IF
                    
                    if (i==15){
                    delLoad.lbldelLoad.setText("Deleting Product ID : "+ productId + " . . .");
                    }//END IF
                    
                    
                    if(i==50){
                       delLoad.dispose();  
                      //CREATE OBJECT DELETE PRODUCT AND PASS PRODUCT ID VALUE
                      deleteProduct dp = new deleteProduct(productId);
                      delStatus = true;
                      playExclamation();
                      new msgBox("Product with ID : "+productId+"\nhas been successfully deleted !","Product Deleted").showinfoMsg();  
                    }//END IF
                    
                    if(i>51){
                        timer.stop();
                        i=0;
                    }//END IF
            }//END PUBLIC VOID
        });
        timer.start();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeletePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeletePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeletePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeletePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeletePanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel ctprodId;
    private javax.swing.JLabel ctprodName;
    private javax.swing.JLabel ctprodPrice;
    private javax.swing.JLabel ctprodQty;
    private javax.swing.JLabel ctprodType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
